# Setup Environment Variables
# Script này sẽ tạo file .env cho frontend

param(
    [string]$BackendPort = "3001"
)

Write-Host "🔧 Setting up environment variables..." -ForegroundColor Cyan
Write-Host ""

$envFile = "frontend\.env"
$envContent = @"
# Frontend Environment Variables
# Generated by setup-env.ps1

# Backend API URL
# Vite proxy sẽ forward /api -> http://localhost:$BackendPort
VITE_API_URL=http://localhost:$BackendPort
"@

# Check if .env already exists
if (Test-Path $envFile) {
    Write-Host "⚠️  File $envFile đã tồn tại!" -ForegroundColor Yellow
    $response = Read-Host "Bạn có muốn ghi đè? (y/N)"
    if ($response -ne "y" -and $response -ne "Y") {
        Write-Host "❌ Hủy bỏ. File giữ nguyên." -ForegroundColor Red
        exit 0
    }
}

# Create .env file
try {
    $envContent | Out-File -FilePath $envFile -Encoding UTF8 -NoNewline
    Write-Host "✅ Đã tạo file: $envFile" -ForegroundColor Green
    Write-Host ""
    Write-Host "📄 Nội dung file:" -ForegroundColor Cyan
    Write-Host "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━" -ForegroundColor Gray
    Write-Host $envContent -ForegroundColor Gray
    Write-Host "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━" -ForegroundColor Gray
    Write-Host ""
    Write-Host "🔄 Tiếp theo:" -ForegroundColor Cyan
    Write-Host "1. Khởi động lại frontend dev server (nếu đang chạy)" -ForegroundColor Yellow
    Write-Host "   Ctrl+C → cd frontend → npm run dev" -ForegroundColor Gray
    Write-Host ""
    Write-Host "2. Kiểm tra proxy hoạt động:" -ForegroundColor Yellow
    Write-Host "   .\test-proxy.ps1" -ForegroundColor Gray
    Write-Host ""
    Write-Host "✅ Done! Frontend sẽ proxy đến: http://localhost:$BackendPort" -ForegroundColor Green
} catch {
    Write-Host "❌ Lỗi khi tạo file: $_" -ForegroundColor Red
    exit 1
}

